%%{init: {"theme": "base", "themeVariables": {"fontFamily": "JetBrains Mono", "fontSize": "10px"}, "htmlLabels": false, "flowchart": {"htmlLabels": false}}}%%
classDiagram
    class NnueNetworks {
        +big_net: Network
        +small_net: Network
        +new(big_path,small_path)
    }

    class Network {
        +feature_tx: FeatureTransformer
        +fc_0: AffineSparseList
        +fc_1: AffineList
        +fc_2: AffineList
        +ac_sqr_0: SqrClippedReLU
        +ac_0: ClippedReLU
        +ac_1: ClippedReLU
        +is_big: bool
        +load(path,is_big) Network
        +evaluate(acc,bucket,stm)
    }

    class ScratchBuffer {
        +transformed_feats: AlignedU8
        +fc_0_out: AlignedI32
        +ac_0_out: AlignedU8
        +fc_1_in: AlignedU8
        +fc_1_out: AlignedI32
        +ac_1_out: AlignedU8
        +fc_2_out: AlignedI32
    }

    NnueNetworks *-- Network
    Network *-- FeatureTransformer
    Network *-- ScratchBuffer
    Network --> AffineTransformSparseInput
    Network --> AffineTransform
    Network --> ClippedReLU
    Network --> SqrClippedReLU
