%%{init: {"theme": "base", "themeVariables": {"fontFamily": "JetBrains Mono", "fontSize": "10px"}, "htmlLabels": false, "flowchart": {"htmlLabels": false}}}%%
classDiagram
    direction TB
    class Between {
        +generate_between() BetweenTbl
        -calc_between(from,to) u64
    }

    class Through {
        +generate_line() ThroughTbl
        -calc_line(from,to) u64
        -extend_ray(from,to) RayMask
    }

    class API {
        +line_between(a,b) u64
        +line_through(sq1,sq2) u64
    }

    Through --> Between : uses BETWEEN table
    API --> Between
    API --> Through
