#import "@preview/hetvid:0.1.0": *

#show: hetvid.with(
  title: [OopsMate: A Chess Engine],
  author: "Swoyam Pokharel",
  affiliation: "BSc (Hons) Computer Science",
  header: "Final Year Project Report",
  date-created: "2026-03-03",
  date-modified: datetime.today().display(),
  abstract: [],
  toc: false,
  body-font: ("Libertinus Serif", "New Computer Modern", "FreeSerif"),
  heading-font: ("New Computer Modern", "Libertinus Serif", "FreeSans"),
  raw-font: ("DejaVu Sans Mono", "JetBrains Mono"),
  math-font: ("New Computer Modern Math"),
  emph-font: ("Libertinus Serif", "New Computer Modern"),
  bib-style: (
    en: "harvard-cite-them-right",
    zh: "gb-7714-2015-numeric",
  ),
)

// Cover page is generated by hetvid.
#pagebreak()

#heading(level: 1, numbering: none, outlined: false, bookmarked: false)[Title and Declaration Sheet]
[To be provided.]

#pagebreak()

#heading(level: 1, numbering: none, outlined: false, bookmarked: false)[Abstract]

OopsMate is a chess engine implemented in Rust. The goal of this project is to evalute how classical search and evaluation techniques affect engine strength and efficiency by implementing features incrementally and benchmarking each release against its predecessor.

#pagebreak()
#outline(depth: 3)

#pagebreak()

#heading(level: 2, numbering: none, outlined: false, bookmarked: false)[Table of Figures]
#outline(target: figure)

#pagebreak()

= Introduction

== Project Briefing

OopsMate is a chess engine written in Rust with the following goals: 
- Build a correct and reasonably strong UCI-compatible engine
- Use the codebase as a benchmarking workbench to quantify how incremental techniques (search optimizations, evaluation improvements, and move ordering) impact performance and playing strength.
- Use OopsMate as the foundation for building and releasing modular Rust crates:
  - `strikes`: Precomputed attack tables for all chess pieces, utilizing `BMI2` for `PEXT` based lookup. This also includes precomputed ray patterns ( `between` and `through`) for constarint-based move generation.
  - `utilities`: Common helper functions for working with `u64` bitboards, square notation and board representation.
  - `nnuebie`: A Rust port of Stockfish’s NNUE evaluation function (HalfKA_HM_v2 architecture), supporting both big and small networks. _This currently is in development and aims to have complete feature parity with stockfish's evaluation, both in terms of speed and accuracy._

== Aims

To build a chess engine in Rust from scratch with no external dependencies and benchmark incremental performance gains by applying and evaluating established chess programming techniques.

== Objectives

- Implement a baseline engine with correct legal move generation and UCI protocol.
- Use bitboards and precomputed attack tables for performant move generation.
- Implement a classical alpha-beta search framework with iterative deepening and a transposition table.
- Integrate and benchmark additional techniques (pruning, move ordering, evaluation improvements) across versions.
- Maintain public-facing benchmark evidence.

== Artefact

The artefact is decomposed into four technical units:

- `OopsMate`: main engine crate (UCI, position state, search, caching).
- `strikes`: attack/ray/path utilities for move generation.
- `utilities`: notation parsing and helper utilities.
- `nnuebie`: NNUE inference crate intended for engine-side integration.

#figure(
  image("artefact-report/artefact-diagrams/overview/architecture-overview.svg", width: 95%),
  caption: [OopsMate's architecture overview],
)

== Academic Question

How do different techniques involved in chess programming affect a chess engine's playing strength and efficiency?

== Scope and Limitations

This project focuses on a CPU-based engine using classical search (the alpha-beta family) and both handcrafted and NNUE based evaluation. It does not attempt to reproduce self-play based reinforcement learning systems (like AlphaZero) due to compute requirements. Benchmarks are constrained by available hardware, time controls, and opponent selection.

== Report Structure

This report follows the final report template. [TODO: add stuff here]

#pagebreak()

= Literature Review

#include "lit_review/lit_review_section.typ"

#pagebreak()

= Project Methodology

The project adopts an incremental development approach: each new technique is implemented as a seperate version so its effect can be measured. This suits chess engine development because the rules and correctness criteria don't change, while performance and strength improvements emerge from iteratively adding and tuning optimizations.


For task management, a Kanban board supports continuous tracking of implementation work, bug fixing, and overall development. [TODO: add stuff here]

#pagebreak()

= Different Tools and Technology

This section justifies the technical stack used to build and evaluate the artefact.

#include "tools-tech/tools_tech_body.typ"

#pagebreak()

= Artefact Designs

#include "artefact-report/artefact_designs_body.typ"

#pagebreak()

= Conclusion

[TODO]
#lorem(50)

#pagebreak()

= Critical Evaluation Of Project

[TODO]
#lorem(50)

#pagebreak()

= Professionalism Report
[TODO: Contribution of `nnuebie` and `strikes`]

#include "professionalism/professionalism_section.typ"

#pagebreak()

= Evidence Of Project Management
[Todo: logsheets & Trello]

#lorem(50)

#pagebreak()

#bibliography("lit_review/refs.bib")

#pagebreak()

= Appendices

#lorem(50)
