#import "@preview/hetvid:0.1.0": *

#show: hetvid.with(
  title: [OopsMate: A Rust Chess Engine Workbench],
  author: "Swoyam Pokharel",
  affiliation: "BSc (Hons) Computer Science",
  header: "Final Year Project Report",
  date-created: "2026-03-03",
  date-modified: datetime.today().display(),
  abstract: [],
  toc: false,
  body-font: ("Libertinus Serif", "New Computer Modern", "FreeSerif"),
  heading-font: ("New Computer Modern", "Libertinus Serif", "FreeSans"),
  raw-font: ("DejaVu Sans Mono", "JetBrains Mono"),
  math-font: ("New Computer Modern Math"),
  emph-font: ("Libertinus Serif", "New Computer Modern"),
  bib-style: (
    en: "harvard-cite-them-right",
    zh: "gb-7714-2015-numeric",
  ),
)

// Cover page is generated by hetvid.
#pagebreak()

= Title and Declaration Sheet

[To be provided.]

#pagebreak()

= Abstract

OopsMate is a chess engine and research workbench implemented in Rust. The project investigates how classical search and evaluation techniques affect engine strength and efficiency by implementing features incrementally and benchmarking each release against its predecessor. The artefact is split into a main UCI engine crate and supporting crates for move-generation primitives and utilities, with an additional NNUE inference crate for neural evaluation integration. This report documents the project motivation, background literature, chosen methodology, tooling, artefact design, and an initial evaluation plan.

#pagebreak()

#heading(level: 1, numbering: none, outlined: false, bookmarked: false)[Contents]

#heading(level: 2, numbering: none, outlined: false, bookmarked: false)[Table of Contents]
#outline(depth: 3)

#pagebreak()

#heading(level: 2, numbering: none, outlined: false, bookmarked: false)[Table of Figures]
#outline(target: figure)

#pagebreak()

= Introduction

== Project Briefing

Chess is a well-scoped domain for studying search, evaluation, and decision-making under tight computational constraints. OopsMate is a chess engine written in Rust with two closely related goals: (1) build a correct and reasonably strong UCI-compatible engine, and (2) use the codebase as a benchmarking workbench to quantify how incremental techniques (search optimizations, evaluation improvements, and move ordering) impact performance and playing strength.

The project includes AI-related components in the form of a neural evaluation function (NNUE). In this report, NNUE is treated as a supervised-learning artifact used for fast inference inside a classical alpha-beta search loop. The engine architecture is therefore hybrid: algorithmic search provides tactical depth, while learned evaluation aims to improve positional assessment.

== Aims

To build a chess engine in Rust from scratch and benchmark incremental performance gains by applying and evaluating established chess programming techniques.

== Objectives

- Implement a baseline engine with correct legal move generation and UCI I/O.
- Use bitboards and precomputed attack tables for performant move generation.
- Implement a classical alpha-beta search framework with iterative deepening and a transposition table.
- Integrate and benchmark additional techniques (pruning, move ordering, evaluation improvements) across versions.
- Maintain public-facing documentation and reproducible benchmark evidence.

== Artefact

The artefact is decomposed into four technical units:

- `OopsMate`: main engine crate (UCI, position state, search, caching).
- `strikes`: attack/ray/path utilities for move generation.
- `utilities`: notation parsing and helper utilities.
- `nnuebie`: NNUE inference crate intended for engine-side integration.

#figure(
  image("artefact-report/artefact-diagrams/overview/architecture-overview.svg", width: 95%),
  caption: [System-wide functional decomposition and architecture overview],
)

== Academic Question

How do different techniques involved in chess programming affect a chess engine's playing strength and efficiency?

== Scope and Limitations

This project focuses on a CPU-based engine using classical search (alpha-beta family) and both handcrafted and NNUE-based evaluation. It does not attempt to reproduce self-play reinforcement learning systems (e.g., AlphaZero-style training) due to compute requirements, nor does it attempt to solve chess end-to-end. Benchmarks are constrained by available hardware, time controls, and opponent selection.

== Report Structure

This report follows the departmental final report template: background and literature underpin the methodology and tooling choices; artefact design documents the implemented system; concluding chapters provide evaluation, reflection, and project management evidence.

#pagebreak()

= Literature Review

#include "lit_review/lit_review_section.typ"

#pagebreak()

= Project Methodology

The project adopts an incremental, experiment-driven development approach: each major technique is implemented as a distinct version so its effect can be measured. This suits chess engine development because the problem domain is well-defined (rules and correctness criteria are fixed), while performance and strength improvements emerge from iteratively adding and tuning optimizations.

For task-level management, a Kanban board supports continuous tracking of implementation work, bug-fixing, and experiments. For report-level planning, milestones align to larger deliverables (baseline engine, search/evaluation upgrades, benchmarking and documentation, final integration and write-up). This hybrid approach provides structure without constraining iterative exploration.

#pagebreak()

= Different Tools and Technology

This section justifies the technical stack used to build and evaluate the artefact.

#include "mid-year-progress/tools_tech_body.typ"

#pagebreak()

= Artefact Designs

The artefact design documentation (diagrams and module-level descriptions) is included from the maintained artefact report sources.

#include "artefact-report/artefact_designs_body.typ"

#pagebreak()

= Conclusion

#lorem(50)

#pagebreak()

= Critical Evaluation Of Project

#lorem(50)

#pagebreak()

= Professionalism Report

#include "professionalism/professionalism_section.typ"

#pagebreak()

= Evidence Of Project Management

#lorem(50)

#pagebreak()

= Reference and Bibliography

#bibliography("lit_review/refs.bib")

#pagebreak()

= Appendices

#lorem(50)
